### ISSUE TITLE
Make sound editor resilient to audio with no samples

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-gui#1388]
When audio has no samples, the offline audio context in the audio effects dies. I'm not sure whether this needs to be fixed by making the effect manager resilient to these kinds of buffers, or if these kinds of buffers should not be creatable in the first place (i'm not sure if you can play them, etc, or even how they are created. Requires some investigation.

```
NotSupportedError: Failed to construct 'OfflineAudioContext': The number of frames provided (0) is less than the minimum bound (1).
  at new e (/lib.min.js:132:19561)
  at t.value (/lib.min.js:132:16531)
  at t.l [as handleEffect] (/lib.min.js:1:8358)
```

**Comment by paulkaplan** [comment]
Fixed
