### ISSUE TITLE
Gui should be able to build with the same version of node as scratch-www

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#1465]
Scratch-www currently uses node 8.x, GUI is built with 6.x. (versions used by travis)

When trying to build gui with node 8.9.1 and npm 5.5.1, there are errors:
```
ERROR in ./src/index.jsx
Module build failed: TypeError: Plugin 3 specified in "/Users/chrisg/projects/scratch-gui/.babelrc" was expected to return a function but returned "undefined"
    at Function.normalisePlugin (/Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:148:15)
    at /Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/chrisg/projects/scratch-gui/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/chrisg/projects/scratch-gui/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/chrisg/projects/scratch-gui/node_modules/babel-loader/lib/index.js:175:20)

ERROR in ./src/examples/blocks-only.jsx
... snip repeated stack trace

ERROR in ./src/examples/compatibility-testing.jsx
... snip repeated stack trace

ERROR in ./src/examples/player.jsx
... snip repeated stack trace
```

**Comment by paulkaplan** [comment]
Hmm so this is strange, I can't actually repro this error even though I know both you and andrew were having issues. I installed node 8.9.1 (like you said) using nvm, it came with npm 5.5.1 like you said, and i was able to install the packages and run build just fine...

**Comment by paulkaplan** [comment]
I was also able to run it successfully on travis using node 8 (see: https://travis-ci.org/paulkaplan/scratch-gui/builds/355904180)

Maybe something changed recently? Would you mind trying again?

**Comment by chrisgarrity** [comment]
GUI is building with node 8 for me now, so maybe an update in one of the dependencies fixed it. (thanks greenkeeper) - I'm closing. We can reopen if it reoccurs

**Comment by luofei614** [comment]
I have the same error ...

**Comment by rschamp** [comment]
This seems to be related to my npm version somehow. I was getting this on `npm@5.3.0`, but `npm install -g npm@latest` followed by `rm -rf node_modules` and `npm install` fixed the issue.
