### ISSUE TITLE
Oops! Something went wrong when adding costume

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1632]
### Expected Behavior

Never Oops

### Actual Behavior

Oops

### Steps to Reproduce
It's kind of hard to reproduce, but I've gotten it to happen a few times now.
1. Add 'forever, next costume' script to the cat and run it
2. Set the selected costume index of the stage to at least 1. That is, add at least 1 backdrop, and select a non-first backdrop in the list of backdrops in the costumes tab
3. Add a bunch of surprise sprites

Eventually you will get a crash. "TypeError: Cannot read property 'assetId' of undefined": this indicates that the renderer is trying to access a costume index that doesn't exist for the current editing target.

![newcostumecrash](https://user-images.githubusercontent.com/2855464/37614289-be1ecad6-2b80-11e8-8a12-79d7b781e89b.gif)

### Operating System and Browser

Windows 10 Chrome

**Comment by Clark-E** [comment]
I can’t confirm this right now, but I’m pretty sure that the exception gets thrown [here](https://github.com/LLK/scratch-gui/blob/75f086e065cdb7fac4aa4e524e6fbd8e1d3f7393/src/components/asset-panel/selector.jsx), line 42. This seems to be the only place in the code where this could happen.

Also, concidering the code in question is related to adding in sprite selectors, there’s a good chance the problem is there.

**Comment by fsih** [comment]
I think this is caused by these 2 separate dispatches in scratch-gui/src/lib/vm-listener-hoc:
```
        onTargetsUpdate: data => {
            dispatch(updateEditingTarget(data.editingTarget));
            dispatch(updateTargets(data.targetList));
        },
```

Because this is 2 separate dispatches instead of 1, there is an instant when you add a new sprite where the editing target isn't in the targets list.

In `scratch-gui/src/containers/costume-tab`'s `componentWillReceiveProps`:
```
        const target = editingTarget && sprites[editingTarget] ? sprites[editingTarget] : stage;
        if (!target || !target.costumes) {
            return;
        }

        // If switching editing targets, update the costume index
        if (this.props.editingTarget !== editingTarget) {
            this.setState({selectedCostumeIndex: target.currentCostume});
        }
```

When the editing target isn't found in the sprites list, it defaults to assuming that you are looking at the stage's costumes. It tries to switch the selected costume index to the selected costume in the stage, which doesn't exist in the new sprite, and crashes.

The relevance of the `forever, next costume` block is to cause the VM to have to spam updateTargets, which makes the bug appear more easily for some reason.

**Comment by fsih** [comment]
Yes, I still get it.

raven.min.js:2 gui Unhandled Error: TypeError: Cannot read property 'assetId' of undefined
    at VirtualMachine.getCostumeSvg (https://llk.github.io/scratch-gui/develop/lib.min.js:28843:68)
    at PaintEditorWrapper.render (https://llk.github.io/scratch-gui/develop/lib.min.js:220830:36)
    at finishClassComponent (https://llk.github.io/scratch-gui/develop/lib.min.js:182875:31)
    at updateClassComponent (https://llk.github.io/scratch-gui/develop/lib.min.js:182852:12)
    at beginWork (https://llk.github.io/scratch-gui/develop/lib.min.js:183227:16)
    at performUnitOfWork (https://llk.github.io/scratch-gui/develop/lib.min.js:185226:16)
    at workLoop (https://llk.github.io/scratch-gui/develop/lib.min.js:185290:26)
    at HTMLUnknownElement.callCallback (https://llk.github.io/scratch-gui/develop/lib.min.js:175544:14)
    at HTMLUnknownElement.d (https://cdn.ravenjs.com/3.22.1/raven.min.js:2:4446)
    at Object.invokeGuardedCallbackDev (https://llk.github.io/scratch-gui/develop/lib.min.js:175583:16)
    at invokeGuardedCallback (https://llk.github.io/scratch-gui/develop/lib.min.js:175440:27)
    at renderRoot (https://llk.github.io/scratch-gui/develop/lib.min.js:185368:7)
    at performWorkOnRoot (https://llk.github.io/scratch-gui/develop/lib.min.js:186016:24)
    at performWork (https://llk.github.io/scratch-gui/develop/lib.min.js:185969:7)
    at requestWork (https://llk.github.io/scratch-gui/develop/lib.min.js:185880:7)
    at scheduleWorkImpl (https://llk.github.io/scratch-gui/develop/lib.min.js:185734:11)
    at scheduleWork (https://llk.github.io/scratch-gui/develop/lib.min.js:185691:12)
    at Object.enqueueSetState (https://llk.github.io/scratch-gui/develop/lib.min.js:181214:7)
    at Connect.Component.setState (https://llk.github.io/scratch-gui/develop/lib.min.js:173875:16)
    at Connect.onStateChange (https://llk.github.io/scratch-gui/develop/lib.min.js:82486:16)
    at Object.dispatch (https://llk.github.io/scratch-gui/develop/lib.min.js:82809:7)
    at Object.dispatch (<anonymous>:1:38399)
    at invokeFunc (https://llk.github.io/scratch-gui/develop/lib.min.js:83224:19)
    at Object.debounced [as scratch-gui/targets/UPDATE_EDITING_TARGET] (https://llk.github.io/scratch-gui/develop/lib.min.js:83304:16)
    at Object.dispatch (https://llk.github.io/scratch-gui/develop/lib.min.js:195022:40)
    at dispatch (<anonymous>:1:27776)
    at VirtualMachine.onTargetsUpdate (https://llk.github.io/scratch-gui/develop/lib.min.js:212344:17)
    at VirtualMachine.EventEmitter.emit (https://llk.github.io/scratch-gui/develop/lib.min.js:7300:20)
    at VirtualMachine.emitTargetsUpdate (https://llk.github.io/scratch-gui/develop/lib.min.js:29177:18)
    at Runtime.<anonymous> (https://llk.github.io/scratch-gui/develop/lib.min.js:28282:19)
    at Runtime.EventEmitter.emit (https://llk.github.io/scratch-gui/develop/lib.min.js:7282:17)
    at Runtime._step (https://llk.github.io/scratch-gui/develop/lib.min.js:25623:22)
    at https://llk.github.io/scratch-gui/develop/lib.min.js:26074:24
    at d (https://cdn.ravenjs.com/3.22.1/raven.min.js:2:4446)
Component stack: 
    in PaintEditorWrapper (created by Connect(PaintEditorWrapper))
    in Connect(PaintEditorWrapper) (created by CostumeTab)
    in div (created by Box)
    in Box (created by AssetPanel)
    in div (created by Box)
    in Box (created by AssetPanel)
    in AssetPanel (created by CostumeTab)
    in CostumeTab (created by Connect(CostumeTab))
    in Connect(CostumeTab) (created by InjectIntl(Connect(CostumeTab)))
    in InjectIntl(Connect(CostumeTab)) (created by GUIComponent)
    in div (created by TabPanel)
    in TabPanel (created by GUIComponent)
    in div (created by UncontrolledTabs)
    in UncontrolledTabs (created by Tabs)
    in Tabs (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in div (created by Box)
    in Box (created by GUIComponent)
    in GUIComponent (created by InjectIntl(GUIComponent))
    in InjectIntl(GUIComponent) (created by GUI)
    in GUI (created by Connect(GUI))
    in Connect(GUI) (created by VMListener)
    in VMListener (created by Connect(VMListener))
    in Connect(VMListener) (created by AppStateWrapper)
    in IntlProvider (created by Connect(IntlProvider))
    in Connect(IntlProvider) (created by AppStateWrapper)
    in Provider (created by AppStateWrapper)
    in AppStateWrapper (created by ProjectLoaderComponent)
    in ProjectLoaderComponent (created by ErrorBoundaryWrapper)
    in ErrorBoundary (created by ErrorBoundaryWrapper)
    in ErrorBoundaryWrapper
a.(anonymous function) @ raven.min.js:2
raven.min.js:2 [react-ga] called ga('send', fieldObject);
raven.min.js:2 [react-ga] with fieldObject: {"hitType":"event","eventCategory":"Error","eventAction":"Fatal Error","eventLabel":"Cannot Read Property 'assetId' of Undefined"}
raven.min.js:2 [react-ga] with trackers: undefined
raven.min.js:2 Uncaught TypeError: Cannot read property 'getWorkspace' of null
    at Blocks.updateToolboxBlockValue (lib.min.js:164407)
    at lib.min.js:164419
    at Array.forEach (<anonymous>)
    at Blocks.onTargetsUpdate (lib.min.js:164418)
    at VirtualMachine.wrapper (lib.min.js:1170)
    at invokeFunc (lib.min.js:83224)
    at trailingEdge (lib.min.js:83271)
    at timerExpired (lib.min.js:83259)
    at d (raven.min.js:2)
2sentry.io/api/273218/store/?sentry_version=7&sentry_client=raven-js%2F3.22.1&sentry_key=42b7d13da8ad4d68b13e57c5e54f9a23 Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
