### ISSUE TITLE
'npm install' fails with npm v. 4.1.2

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2343]
Running npm install failed with the following error:

```
scratch-gui  $ npm install
npm ERR! Darwin 17.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'forEach' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/karishma/Projects/scratch-gui/npm-debug.log
```

This was the full debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@4.1.2
3 info using node@v7.7.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 verbose stack TypeError: Cannot read property 'forEach' of undefined
13 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:12)
13 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
13 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/copy-tree.js:22:18
13 verbose stack     at Array.forEach (native)
13 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:13)
13 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:10:3)
13 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/copy-tree.js:22:18
13 verbose stack     at Array.forEach (native)
13 verbose stack     at copyModuleList (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:21:13)
13 verbose stack     at copyTree (/usr/local/lib/node_modules/npm/lib/install/copy-tree.js:15:3)
14 verbose cwd /Users/karishma/Projects/scratch-gui
15 error Darwin 17.5.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
17 error node v7.7.1
18 error npm  v4.1.2
19 error Cannot read property 'forEach' of undefined
20 error If you need help, you may report this error at:
20 error     <https://github.com/npm/npm/issues>
21 verbose exit [ 1, true ]
```

**Comment by paulkaplan** [comment]
Hmm I'm going to close this because it is being run with a node version we do not use on the CI.
