### ISSUE TITLE
Travis build failed on "Working with the how-to library › Choosing a how-to" test

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4887]
This PR build on Travis failed: https://travis-ci.org/LLK/scratch-gui/builds/535343291?utm_source=github_status&utm_medium=notification

...with this error:

```
 FAIL  test/integration/how-tos.test.js
  ● Working with the how-to library › Choosing a how-to
    WebDriverError: element click intercepted: Element <span>...</span> is not clickable at point (158, 76). Other element would receive the click: <div class="loader_background_2DPrW">...</div>
      (Session info: headless chrome=74.0.3729.157)
      (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.4.0-101-generic x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.click()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at test/helpers/selenium-helper.js:110:73
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

```

I restarted the build.

**Comment by thisandagain** [comment]
@benjiwheeler @BryceLTaylor Is this still an issue?
