### ISSUE TITLE
"Change categories" test in exampltes.test.js failing inconsistently

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#4902]
In https://travis-ci.org/LLK/scratch-gui/builds/541819019 , we saw this failure:

```
FAIL test/integration/examples.test.js
  ● blocks example › Change categories
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=75.0.3770.80)
      (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.4.0-101-generic x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.isDisplayed()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.isDisplayed (node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
      at test/helpers/selenium-helper.js:89:32
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

Retrying the build, this same test passed: https://travis-ci.org/LLK/scratch-gui/builds/541876228

**Comment by kchadha** [comment]
Seen again three builds in a row last night on gui develop:
https://travis-ci.org/LLK/scratch-gui/jobs/547545197#L4703
https://travis-ci.org/LLK/scratch-gui/builds/547555384#L4703
https://travis-ci.org/LLK/scratch-gui/builds/547560182#L4703

**Comment by benjiwheeler** [comment]
Closing this, per #4934; filed follow-up issue https://github.com/LLK/scratch-gui/issues/4950
