### ISSUE TITLE
Flaky GUI Integration Test in blocks.test.js

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#5015]
Flaky Test: `Working with the blocks › Renaming costume changes the default costume name in the toolbox`

Seen in the attached build log:
[flaky-tests-gui.txt](https://github.com/LLK/scratch-gui/files/3423521/flaky-tests-gui.txt)

**Comment by benjiwheeler** [comment]
Shortly after passing tests, I reran a GUI build and it failed:

```
FAIL test/integration/blocks.test.js (60.717s)
  ● Working with the blocks › Renaming costume changes the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=76.0.3809.132)
      (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Linux 4.4.0-101-generic x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.isDisplayed()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.isDisplayed (node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
      at test/helpers/selenium-helper.js:89:32
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```
