### ISSUE TITLE
Flaky integration test: FAIL test/integration/blocks.test.js

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#5177]
```
FAIL test/integration/blocks.test.js (79.049s)
  ● Working with the blocks › Adding a sound DOES update the default sound name in the toolbox
    TimeoutError: findByXpath timed out for path: //body//*[@id='react-tabs-1']//*[contains(text(), 'A Bass')]
    Wait timed out after 20006ms
      
      at node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: findByXpath timed out for path: //body//*[@id='react-tabs-1']//*[contains(text(), 'A Bass')]
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at thenableWebDriverProxy.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at SeleniumHelper.findByXpath (test/helpers/selenium-helper.js:87:26)
      at SeleniumHelper.wrapper [as findByXpath] (node_modules/lodash.bindall/index.js:550:15)
      at SeleniumHelper.findByText (test/helpers/selenium-helper.js:95:19)
      at SeleniumHelper.wrapper [as findByText] (node_modules/lodash.bindall/index.js:550:15)
      at SeleniumHelper.clickText (test/helpers/selenium-helper.js:118:19)
      at wrapper (node_modules/lodash.bindall/index.js:550:15)
      at _callee12$ (test/integration/blocks.test.js:243:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (test/integration/blocks.test.js:2:278)
      at _next (test/integration/blocks.test.js:2:616)
          at <anonymous>
```

**Comment by fsih** [comment]
This has failed 3 times in a row for my build. Looks like it's been failing for at least 8 hours: https://travis-ci.org/LLK/scratch-gui/builds
