### ISSUE TITLE
npm run build BUILD_MODE=dist  EntryModuleNotFoundError: Entry module not found: Error: 

### ISSUE THREAD

**Issue by maxianbin** [LLK/scratch-gui#5320]
npm run build BUILD_MODE=dist  has some errors :

70% [0] building 0/0 modules 0 activeEntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'dist' in 'D:\Scratch\scratch-gui'
    at moduleFactory.create (D:\Scratch\scratch-gui\node_modules\webpack\lib\Compilation.js:1075:31)
    at factory (D:\Scratch\scratch-gui\node_modules\webpack\lib\NormalModuleFactory.js:401:22)
    at resolver (D:\Scratch\scratch-gui\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (D:\Scratch\scratch-gui\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at D:\Scratch\scratch-gui\node_modules\neo-async\async.js:2830:7
    at D:\Scratch\scratch-gui\node_modules\neo-async\async.js:6877:13
    at normalResolver.resolve (D:\Scratch\scratch-gui\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:213:14)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn41 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:28:1)
    at resolver.doResolve (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:30:40)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at args (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\forEachBail.js:30:14)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn42 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (D:\Scratch\scratch-gui\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve 'dist' in 'D:\Scratch\scratch-gui'
  Parsed request is a module
  using description file: D:\Scratch\scratch-gui\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\Scratch\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\Scratch\scratch-gui\node_modules
        using description file: D:\Scratch\scratch-gui\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\Scratch\scratch-gui\package.json (relative path: ./node_modules/dist)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Scratch\scratch-gui\node_modules\dist doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\Scratch\scratch-gui\node_modules\dist.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\Scratch\scratch-gui\node_modules\dist.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Scratch\scratch-gui\node_modules\dist.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\Scratch\scratch-gui\node_modules\dist.json doesn't exist
            as directory
              D:\Scratch\scratch-gui\node_modules\dist doesn't exist

**Comment by hu19940121** [comment]
me too

**Comment by hu19940121** [comment]
anybody resolve this problem？

**Comment by apple502j** [comment]
what command did you use? `BUILD_MODE=dist npm run build`?

**Comment by apple502j** [comment]
Also, for things using scratch-www, you should use cygwin or WSL.

**Comment by hu19940121** [comment]
> what command did you use? `BUILD_MODE=dist npm run build`?
user `npm run build BUILD_MODE=dist` in scratch-gui

**Comment by maxianbin** [comment]
> Also, for things using scratch-www, you should use cygwin or WSL.

it works
