### ISSUE TITLE
Flaky integration test: blocks.test.js

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#5429]
Passed when I reran it

FAIL test/integration/blocks.test.js (46.004s)
  ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=80.0.3987.87)
      (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.click()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at test/helpers/selenium-helper.js:124:73
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by fsih** [comment]
I just got a different failure for the same integration test

FAIL test/integration/blocks.test.js (48.864s)
  ● Working with the blocks › "See inside" after being on project page re-initializing variables
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=80.0.3987.87)
      (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.isDisplayed()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.isDisplayed (node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
      at test/helpers/selenium-helper.js:95:32
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by fsih** [comment]
Failed again

FAIL test/integration/blocks.test.js (45.965s)
  ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=80.0.3987.87)
      (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.click()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at test/helpers/selenium-helper.js:124:73
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by fsih** [comment]
The flakiness might have been caused by updating chromedriver from version 78 to version 80, which we had to do because all of the integration tests were failing...

The failures were a huge pain last night, so I'm going to mark this as critical

**Comment by BryceLTaylor** [comment]
The error messages are not very helpful in figuring out which line of the test is actually failing.  All I can tell is that it usually fails while trying to click a web element (with clickText() ).  One of the times it failed trying to find a web element (with findByXpath() ).  findByXpath gets used in pretty much every function we call.

**Comment by fsih** [comment]
I got this one again

 FAIL  test/integration/blocks.test.js (43.191s)
  ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=80.0.3987.87)
      (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.click()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at test/helpers/selenium-helper.js:124:73
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by adroitwhiz** [comment]
@BryceLTaylor This [is still flaking out for me](https://travis-ci.org/github/LLK/scratch-gui/builds/661582627).

**Comment by benjiwheeler** [comment]
@adroitwhiz wrote:

> @BryceLTaylor This is still flaking out for me.

Me too -- it reliably fails locally, if I run it in headless mode.

See more notes at https://github.com/LLK/scratch-gui/pull/4871#issuecomment-598543686

Proposal: we should try taking out the `this.driver.wait(el.isDisplayed()` portion of findByXPath, or provide a param to disable it.

**Comment by benjiwheeler** [comment]
FYI, @adroitwhiz's error was:

```
 FAIL  test/integration/blocks.test.js (50.772s)
  ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=80.0.3987.132)
      (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.click()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at test/helpers/selenium-helper.js:124:73
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```
