### ISSUE TITLE
Flaky test: test/integration/blocks.test.js

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#5480]
test/integration/blocks.test.js failed twice before passing

Unfortunately I have accidentally overwritten my paste buffer, but I think it was this one:

Working with the blocks › Renaming costume changes the default costume name in the toolbox
StaleElementReferenceError: stale element reference: element is not attached to the page document

**Comment by fsih** [comment]
I got it again!

FAIL test/integration/blocks.test.js (41.849s)
  ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=80.0.3987.122)
      (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.isDisplayed()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.isDisplayed (node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
      at test/helpers/selenium-helper.js:95:32
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by fsih** [comment]
Got this flake again

FAIL test/integration/blocks.test.js (50.23s)
10921
 ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
10922
10923
   StaleElementReferenceError: stale element reference: element is not attached to the page document
10924
     (Session info: headless chrome=80.0.3987.149)
10925
     (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.15.0-1028-gcp x86_64)
10926
    
10927
     at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
10928
     at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
10929
     at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
10930
         at <anonymous>
10931
     at process._tickCallback (internal/process/next_tick.js:189:7)
10932
     From: Task: WebElement.click()
10933
     at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
10934
     at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
10935
     at WebElement.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
10936
     at test/helpers/selenium-helper.js:124:73
10937
     at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
10938
     at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
10939
     at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
10940
     at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
10941
     at node_modules/selenium-webdriver/lib/promise.js:668:7
10942
         at <anonymous>
10943
     at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by fsih** [comment]
Got it again

FAIL test/integration/blocks.test.js (52.425s)
  ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=80.0.3987.149)
      (Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.isDisplayed()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.isDisplayed (node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
      at test/helpers/selenium-helper.js:95:32
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by fsih** [comment]
I hit this again today

**Comment by fsih** [comment]
I hit this every time I deploy, it happens like half the time

 FAIL  test/integration/blocks.test.js (46.755s)
  ● Working with the blocks › Adding costumes DOES update the default costume name in the toolbox
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=81.0.4044.129)
      (Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebElement.isDisplayed()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.isDisplayed (node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
      at test/helpers/selenium-helper.js:95:32
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by fsih** [comment]
@BryceLTaylor do you mind looking at https://github.com/LLK/scratch-gui/pull/5516 ? looks promising!

**Comment by fsih** [comment]
Got it again
