### ISSUE TITLE
FAIL test/integration/localization.test.js Localization › Switching languages

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#5619]
I have hit this a couple times today. It passes for me locally

FAIL test/integration/localization.test.js (30.112s)
  ● Localization › Switching languages
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:498:11)
      at tryOnTimeout (timers.js:323:5)
      at Timer.listOnTimeout (timers.js:290:5)
  ● Localization › Loading with locale shows correct blocks
    WebDriverError: unknown error: Chrome failed to start: exited abnormally.
      (chrome not reachable)
      (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
      (Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Linux 4.15.0-1028-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebDriver.createSession()
      at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (node_modules/selenium-webdriver/index.js:642:16)
      at SeleniumHelper.getDriver (test/helpers/selenium-helper.js:73:7)
      at wrapper (node_modules/lodash.bindall/index.js:550:15)
      at _callee2$ (test/integration/localization.test.js:29:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (test/integration/localization.test.js:2:278)
      at _next (test/integration/localization.test.js:2:616)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
      From: Task: WebDriver.navigate().to(file:///home/travis/build/LLK/scratch-gui/build/index.html?locale=de)
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Navigation.to (node_modules/selenium-webdriver/lib/webdriver.js:1133:25)
      at thenableWebDriverProxy.get (node_modules/selenium-webdriver/lib/webdriver.js:988:28)
      at SeleniumHelper.loadUri (test/helpers/selenium-helper.js:108:7)
      at wrapper (node_modules/lodash.bindall/index.js:550:15)
      at _callee3$ (test/integration/localization.test.js:62:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (test/integration/localization.test.js:2:278)
      at _next (test/integration/localization.test.js:2:616)
      at test/integration/localization.test.js:2:781
          at new Promise (<anonymous>)
      at Object.<anonymous> (test/integration/localization.test.js:2:522)
          at new Promise (<anonymous>)
          at <anonymous>

**Comment by kchadha** [comment]
Taking the milestone off this since @rschamp and I think it would be good to prioritize getting builds working on Circle CI. Tests seemed to be less flaky there on a whole.

**Comment by kchadha** [comment]
@BryceLTaylor do these tests need to be skipped?

**Comment by BryceLTaylor** [comment]
I made some changes that I think should make this test more stable.  It will be hard to know for sure that it is less flaky without just waiting and letting the tests run a number of times.  I'm going to close this issue and reopen if the tests fail again.
