### ISSUE TITLE
Integration tests keep failing on GUI

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#6125]
A lot of different ones have failed for me

**Comment by fsih** [comment]
https://travis-ci.org/github/LLK/scratch-gui/builds/721183899

FAIL  test/integration/menu-bar.test.js (30.232s)
  ● Menu bar settings › File->New should be enabled
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
  ● Menu bar settings › File->Load should be enabled
    SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 83
      (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.15.0-1077-gcp x86_64)

**Comment by fsih** [comment]
FAIL  test/integration/localization.test.js (30.334s)
  ● Localization › Switching languages
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
  ● Localization › Loading with locale shows correct blocks
    SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 83
      (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.15.0-1077-gcp x86_64)

**Comment by fsih** [comment]
FAIL  test/integration/connection-modal.test.js (30.106s)
  ● Hardware extension connection modal › Message saying Scratch Link is unavailable (BLE)
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
  ● Hardware extension connection modal › Message saying Scratch Link is unavailable (BT)
    NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

**Comment by fsih** [comment]
FAIL  test/integration/backpack.test.js (30.082s)
  ● Working with the how-to library › Backpack is "Coming Soon" without backpack host param
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
  ● Working with the how-to library › Backpack can be expanded with backpack host param
    SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 83

**Comment by fsih** [comment]
FAIL  test/integration/project-state.test.js (30.285s)
  ● Project state › File->New resets project title
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
 FAIL  test/integration/stage-size.test.js (30.162s)
  ● Loading scratch gui › Switching small/large stage after highlighting and deleting sprite
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
 FAIL  test/integration/tutorials-shortcut.test.js (30.09s)
  ● Working with shortcut to Tutorials library › opens with the Tutorial Library showing
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
  ● Working with shortcut to Tutorials library › can open hidden tutorials
    SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 83

**Comment by fsih** [comment]
FAIL  test/integration/how-tos.test.js (30.169s)
  ● Working with the how-to library › Choosing a how-to
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)

**Comment by fsih** [comment]
I've rerun 3 times, so it seems like it's not flakiness

**Comment by fsih** [comment]
Tests are all working fine for me locally. I tried 12.14.1 and 10.22.0 (the version that Travis uses)

**Comment by fsih** [comment]
Update chromedriver PR has travis working but an integration test is failing on circle
 FAIL  test/integration/stage-size.test.js (30.075s)
  ● Loading scratch gui › Switching small/large stage after highlighting and deleting sprite

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)

Test Suites: 1 failed, 1 skipped, 5 passed, 6 of 7 total
Tests:       1 failed, 5 skipped, 20 passed, 26 total
Snapshots:   0 total
Time:        88.495s
Ran all test suites matching /test\/integration\/backpack.test.js|test\/integration\/connection-modal.test.js|test\/integration\/examples.test.js|test\/integration\/localization.test.js|test\/integration\/project-loading.test.js|test\/integration\/sounds.test.js|test\/integration\/stage-size.test.js/i.

**Comment by fsih** [comment]
It worked on rerun, so I guess that was a flake

**Comment by fsih** [comment]
Another failure in travis 
FAIL  test/integration/project-loading.test.js (9.407s)
  ● Loading scratch gui › Loading projects by ID › Creating new project resets active tab to Code tab
    StaleElementReferenceError: stale element reference: element is not attached to the page document
      (Session info: headless chrome=85.0.4183.83)
      (Driver info: chromedriver=85.0.4183.83 (94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}),platform=Linux 4.15.0-1077-gcp x86_64)
      
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
      From: Task: WebElement.isDisplayed()
      at thenableWebDriverProxy.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.isDisplayed (node_modules/selenium-webdriver/lib/webdriver.js:2362:17)
      at test/helpers/selenium-helper.js:96:32
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at node_modules/selenium-webdriver/lib/promise.js:668:7
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by fsih** [comment]
It worked on rerun!
