### ISSUE TITLE
Error message when loading the.sb3 file to ArrarBuff from the server

### ISSUE THREAD

**Issue by ESWN-1234** [LLK/scratch-gui#8676]
### Expected Behavior
Files in the local service can be loaded into the project via http
### Actual Behavior
Placing the file on a remote server and downloading it over http cannot be loaded into the project and an error is reported
assert.js:12 
Uncaught (in promise) Error: Non-ascii character in FixedAsciiString 
at assert (assert.js:12:1) 
at FixedAsciiString. read (byte-primitives.js:343:1) 
at SB1Signature. get [as version] (byte-primitives.js:100:1) 
at SB1Signature. equals (byte-packets.js:56:1) 
at SB1Signature. validate (sb1-file-packets.js:30:1) 
at new SB1File (sb1-file.js:20:1) 
at virtual-machine.js:333:1 
### Steps to Reproduce
containers\gui.js

componentDidMount () { 
setIsScratchDesktop(this.props.isScratchDesktop); 
this.props.onStorageInit(storage); 
this.props.onVmInit(this.props.vm); 
const url=this.getQueryParameter("file"); 
fetch(url,{ 
method: 'GET', 
mode: "no-cors" 
}) 
.then(response=>response.blob()) 
.then(blob=>{ 
blob.arrayBuffer().then(buffer=>{ 
this.props.vm.loadProject(buffer) 
.then(()=>{ 
console.log("sfsdgsfgsdfg") 
}) 
}) 
}) 
.catch(error=>{ 
console.log("Failed to load the file remotely",error) 
alert("Failed to load the file remotely") 
}) 
}
### Operating System and Browser
winindows 11 edge and google

**Comment by ESWN-1234** [comment]
Look at the source code seems to have a signature mechanism, what is the solution

**Comment by IJayHuI** [comment]
I have the same question
