### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by tianrking** [LLK/scratch-gui#8678]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/w0x7ce/Desktop/scratch-gui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/w0x7ce/Desktop/scratch-gui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/w0x7ce/Desktop/scratch-gui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/w0x7ce/Desktop/scratch-gui/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/w0x7ce/Desktop/scratch-gui/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/w0x7ce/Desktop/scratch-gui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/w0x7ce/Desktop/scratch-gui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/w0x7ce/Desktop/scratch-gui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/w0x7ce/Desktop/scratch-gui/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/w0x7ce/Desktop/scratch-gui/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/w0x7ce/Desktop/scratch-gui/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

**Comment by tianrking** [comment]
https://github.com/LLK/scratch-gui/issues/7890
