### ISSUE TITLE
When I npm install scratch-gui, request to https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip failed

### ISSUE THREAD

**Issue by tomorrow307** [LLK/scratch-gui#9012]
> scratch-gui@1.9.9 prepublish
> node scripts/prepublish.mjs

Downloading https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip
FetchError: request to https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip failed, reason: connect ETIMEDOUT 162.125.32.10:443
    at ClientRequest.<anonymous> (D:\lxj\myelectron\scratch\scratch-gui\node_modules\cross-fetch\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:369:20)
    at TLSSocket.socketErrorListener (node:_http_client:472:9)
    at TLSSocket.emit (node:events:369:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
npm ERR! code 1
npm ERR! path D:\lxj\myelectron\scratch\scratch-gui
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/prepublish.mjs

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lxj\AppData\Local\npm-cache\_logs\2023-06-20T08_28_43_088Z-debug.log

**Comment by dbgoa** [comment]
Is the problem solved？I'm having the same issue.

**Comment by You548** [comment]
Please Download This : https://download.scratch.mit.edu/microbit/scratch-microbit.hex.zip

**Comment by little8jie** [comment]
I also encountered this issue in China and cannot open this address. How to solve it, thank you

**Comment by ghost** [comment]
if Browser download, please use this link:[if browser download](https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip)

**Comment by JiafengLiao** [comment]
Guys, Greetings from China, 
I solved it by manually downloading and extracting hex file plus a few lines of code modification.

Here are the steps:
 1. download zip file from "https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip" on browser or wget
 2. extract zip file to static/microbit。
 3. check "static\microbit\scratch-microbit-1.2.0.hex" exist
 4. modify function "downloadMicrobitHex" in "scripts\prepublish.mjs" as follow to skip downloading and extracting, and read hex file directly from local instead.


```
const downloadMicrobitHex = async () => {
    const relativeHexDir = path.join('static', 'microbit');
    const hexFileName = "scratch-microbit-1.2.0.hex"
    const relativeHexFile = path.join(relativeHexDir, hexFileName);
    const relativeGeneratedDir = path.join('src', 'generated');
    const relativeGeneratedFile = path.join(relativeGeneratedDir, 'microbit-hex-url.cjs');
    const absoluteGeneratedDir = path.join(basePath, relativeGeneratedDir);
    fs.mkdirSync(absoluteGeneratedDir, {recursive: true});
    const absoluteGeneratedFile = path.join(basePath, relativeGeneratedFile);
    fs.writeFileSync(
        absoluteGeneratedFile,
        [
            '// This file is generated by scripts/prepublish.mjs',
            '// Do not edit this file directly',
            '// This file relies on a loader to turn this `require` into a URL',
            `module.exports = require('./${path.relative(relativeGeneratedDir, relativeHexFile)}');`,
            '' // final newline
        ].join('\n')
    );
    console.info(`Wrote ${relativeGeneratedFile}`);
};
```



@tomorrow307 @dbgoa @little8jie

**Comment by huangjiarong** [comment]
> 2\. microbit

thanks, i do it and solve the problem

**Comment by lishenjian** [comment]
> 

牛

**Comment by cnmarky** [comment]
@JiafengLiao thanks!

**Comment by cocospy** [comment]
excellent solution！

**Comment by hunluanyuba** [comment]
上边的朋友说得对，遇到这个问题的基本都是中国的，翻墙软件似乎并不能让npm翻墙
就是用浏览器下载https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip
加压后放在static\microbit\scratch-microbit-1.2.0.hex
最后修改scripts\prepublish.mjs中的downloadMicrobitHex函数代码看上边那个朋友的

**Comment by Applewan** [comment]
按照上面给出的方案，可以正常运行成功；但是我在运行 npm start 启动的时候，报错：
ERROR in ./src/generated/microbit-hex-url.cjs
Module not found: Error: Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D:\Scratch\Scratch-Testing\scratch-gui\src\generated'
请问有没有什么好的解决方案？

**Comment by JiafengLiao** [comment]
> 按照上面给出的方案，可以正常运行成功；但是我在运行 npm start 启动的时候，报错： ERROR in ./src/generated/microbit-hex-url.cjs Module not found: Error: Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D:\Scratch\Scratch-Testing\scratch-gui\src\generated' 请问有没有什么好的解决方案？

是完全按照步骤来的吗？看起来像是路径问题

**Comment by jfyear1994** [comment]
@Applewan generated/microbit-hex-url.cjs
module.exports = require('./../../static/microbit/scratch-microbit-1.2.0.hex');

**Comment by nsgdsb** [comment]
还是没有解决，该怎么办

**Comment by nsgdsb** [comment]
> 按照上面给出的方案，可以正常运行成功;但是我在运行 npm start 启动的时候，报错： ERROR in ./src/generated/microbit-hex-url.cjs Module not found： Error： Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D：\Scratch\Scratch-Testing\scratch-gui\src\generated' 请问有没有什么好的解决方案？

最后您是怎么解决的

**Comment by JiafengLiao** [comment]
> > 按照上面给出的方案，可以正常运行成功;但是我在运行 npm start 启动的时候，报错： ERROR in ./src/generated/microbit-hex-url.cjs Module not found： Error： Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D：\Scratch\Scratch-Testing\scratch-gui\src\generated' 请问有没有什么好的解决方案？
> 
> 最后您是怎么解决的

报错是啥

**Comment by KoEkko** [comment]
> @Applewan generated/microbit-hex-url.cjs module.exports = require('./../../static/microbit/scratch-microbit-1.2.0.hex');

Why do I have this problem? How can I solve it? Thank you！

ERROR in ./src/generated/microbit-hex-url.cjs
    Module not found: Error: Can't resolve './../../static/microbit/scratch-microbit-1.2.0.hex' in 'D:\Baidu\scratch-gui\src\generated'
     @ ./src/generated/microbit-hex-url.cjs 1:17-78
     @ ./src/lib/microbit-update.js
     @ ./src/containers/connection-modal.jsx
     @ ./src/components/gui/gui.jsx
     @ ./src/containers/gui.jsx
     @ ./src/playground/compatibility-testing.jsx

**Comment by KoEkko** [comment]
> > 按照上面给出的方案，可以正常运行成功;但是我在运行 npm start 启动的时候，报错： ERROR in ./src/generated/microbit-hex-url.cjs Module not found： Error： Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D：\Scratch\Scratch-Testing\scratch-gui\src\generated' 请问有没有什么好的解决方案？
> 
> 最后您是怎么解决的

请问您解决了吗

**Comment by Chenchenweihang** [comment]
Hello！
My issue is followed：
 ERROR in ./src/lib/microbit-update.js
    Module not found: Error: Can't resolve '../generated/microbit-hex-url.cjs' in 'E:\scratch-gui\src\lib'
     @ ./src/lib/microbit-update.js 12:0-55 84:23-29
     @ ./src/containers/connection-modal.jsx
     @ ./src/components/gui/gui.jsx
     @ ./src/containers/gui.jsx
     @ ./src/playground/player.jsx
    Child HtmlWebpackCompiler:
                              Asset      Size               Chunks  Chunk Names
        __child-HtmlWebpackPlugin_0  4.62 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
        Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/playground/index.ejs] 599 bytes {HtmlWebpackPlugin_0} [built]
i ｢wdm｣: Failed to compile.


May I ask how you can solve this problem.

**Comment by JiafengLiao** [comment]
> 4\. scripts\prepublish.mjs

looks like the path is not correctly set. For those who encountered "Can't resolve '****/microbit-hex-url.cjs'" problem. Please check your code in 'scripts\prepublish.mjs' with the code snippet I post. And check if microbit-hex-url.cjs stored in the path 'src/generate/'

**Comment by gms335** [comment]
module.exports = require('./..\..\static\microbit\scratch-microbit-1.2.0.hex'); 
这句中的“\”改成“/”，如下：
module.exports = require('./../../static/microbit/scratch-microbit-1.2.0.hex');

**Comment by XESDog** [comment]
是否有高端一点的解法，scratch-desktop也报该问题，却没有相关的script去修改。

我本人有梯子，且设置了命令行代理(设置了http_proxy https_proxy all_proxy)，能够通过wget https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip 下载到该文件。

但是，执行npm install 的时候依然报错，真是日了狗了。
npm ERR! FetchError: request to https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip failed, reason: connect ETIMEDOUT 156.233.67.243:443
npm ERR!     at ClientRequest.<anonymous> (/Users/zheng/.npm/_cacache/tmp/git-cloneA5MTJ7/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1491:11)
npm ERR!     at ClientRequest.emit (node:events:517:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR!     at TLSSocket.emit (node:events:517:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   type: 'system',
npm ERR!   errno: 'ETIMEDOUT',
npm ERR!   code: 'ETIMEDOUT'

**Comment by huiye19** [comment]
> [wudaochen](/wudaochen)

@wudaochen Hello, I met the same error with yours. May I know have you addressed it?

**Comment by XBZD-WDD** [comment]
> > 4. scripts\prepublish.mjs
> 
> looks like the path is not correctly set. For those who encountered "Can't resolve '****/microbit-hex-url.cjs'" problem. Please check your code in 'scripts\prepublish.mjs' with the code snippet I post. And check if microbit-hex-url.cjs stored in the path 'src/generate/'

**Comment by daydayhappychao** [comment]
This isn't a great solution, I'd love some help with this.

**Comment by wulup1120** [comment]
> 是否有高端一点的解法，scratch-desktop也报该问题，却没有相关的script去修改。
> 
> 我本人有梯子，且设置了命令行代理(设置了http_proxy https_proxy all_proxy)，能够通过wget https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip 下载到该文件。
> 
> 但是，执行npm install 的时候依然报错，真是日了狗了。 npm ERR! FetchError: request to https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip failed, reason: connect ETIMEDOUT 156.233.67.243:443 npm ERR! at ClientRequest. (/Users/zheng/.npm/_cacache/tmp/git-cloneA5MTJ7/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1491:11) npm ERR! at ClientRequest.emit (node:events:517:28) npm ERR! at TLSSocket.socketErrorListener (node:_http_client:501:9) npm ERR! at TLSSocket.emit (node:events:517:28) npm ERR! at emitErrorNT (node:internal/streams/destroy:151:8) npm ERR! at emitErrorCloseNT (node:internal/streams/destroy:116:3) npm ERR! at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { npm ERR! type: 'system', npm ERR! errno: 'ETIMEDOUT', npm ERR! code: 'ETIMEDOUT'

解决了吗兄弟？解决了给我说下，我也是这个问题  到desktop就这个错误

**Comment by wulup1120** [comment]
@XESDog   解决了吗？

**Comment by xilinshuishi** [comment]
> @XESDog 解决了吗？

这样修改可以：
const downloadMicrobitHex = async () => {
    const relativeHexDir = path.join('static', 'microbit');
    const hexFileName = "scratch-microbit-1.2.0.hex"
    const relativeHexFile = path.join(relativeHexDir, hexFileName);
    const relativeGeneratedDir = path.join('src', 'generated');
    const relativeGeneratedFile = path.join(relativeGeneratedDir, 'microbit-hex-url.cjs');
    const absoluteGeneratedDir = path.join(basePath, relativeGeneratedDir);
    fs.mkdirSync(absoluteGeneratedDir, {recursive: true});
    const absoluteGeneratedFile = path.join(basePath, relativeGeneratedFile);
    fs.writeFileSync(
        absoluteGeneratedFile,
        [
            '// This file is generated by scripts/prepublish.mjs',
            '// Do not edit this file directly',
            '// This file relies on a loader to turn this `require` into a URL',
            `module.exports = require('./../../static/microbit/scratch-microbit-1.2.0.hex');`,
            '' // final newline
        ].join('\n')
    );
    console.info(`Wrote ${relativeGeneratedFile}`);
};

**Comment by Sempre0721** [comment]
There is no generated folder in my directory, and I couldn't find any microbit-hex-url.cjs file.Where should I write "module.exports = require（'./../../static/microbit/scratch-microbit-1.2.0.hex'）;"?

**Comment by Sempre0721** [comment]
I know how to console this problem.
just copy it:
const downloadMicrobitHex = async () => {
    const relativeHexDir = path.join('static', 'microbit');
    const hexFileName = "scratch-microbit-1.2.0.hex";
    const relativeHexFile = path.join(relativeHexDir, hexFileName);
    const relativeGeneratedDir = path.join('src', 'generated');
    const relativeGeneratedFile = path.join(relativeGeneratedDir, 'microbit-hex-url.cjs');
    const absoluteGeneratedDir = path.join(basePath, relativeGeneratedDir);
    fs.mkdirSync(absoluteGeneratedDir, {recursive: true});
    const absoluteGeneratedFile = path.join(basePath, relativeGeneratedFile);
    fs.writeFileSync(
        absoluteGeneratedFile,
        [
            '// This file is generated by scripts/prepublish.mjs',
            '// Do not edit this file directly',
            '// This file relies on a loader to turn this require into a URL',
            `module.exports = require('./../../static/microbit/${hexFileName}');`,
            '' // final newline
        ].join('\n')
    );
    console.info(`Wrote ${relativeGeneratedFile}`);
};

**Comment by xilinshuishi** [comment]
> I know how to console this problem. just copy it: const downloadMicrobitHex = async () => { const relativeHexDir = path.join('static', 'microbit'); const hexFileName = "scratch-microbit-1.2.0.hex"; const relativeHexFile = path.join(relativeHexDir, hexFileName); const relativeGeneratedDir = path.join('src', 'generated'); const relativeGeneratedFile = path.join(relativeGeneratedDir, 'microbit-hex-url.cjs'); const absoluteGeneratedDir = path.join(basePath, relativeGeneratedDir); fs.mkdirSync(absoluteGeneratedDir, {recursive: true}); const absoluteGeneratedFile = path.join(basePath, relativeGeneratedFile); fs.writeFileSync( absoluteGeneratedFile, [ '// This file is generated by scripts/prepublish.mjs', '// Do not edit this file directly', '// This file relies on a loader to turn this require into a URL', `module.exports = require('./../../static/microbit/${hexFileName}');`, '' // final newline ].join('\n') ); console.info(`Wrote ${relativeGeneratedFile}`); };

yes, you are right, cool

**Comment by Applewan** [comment]
已解决，多谢



发自我的iPhone


------------------ Original ------------------
From: 定位大师 ***@***.***&gt;
Date: Mon,Sep 23,2024 3:48 PM
To: scratchfoundation/scratch-gui ***@***.***&gt;
Cc: Applewan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [scratchfoundation/scratch-gui] When I npm install scratch-gui,request to https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zipfailed (Issue #9012)





 
@XESDog   解决了吗？

**Comment by cacf10** [comment]
> Guys, Greetings from China, I solved it by manually downloading and extracting hex file plus a few lines of code modification.
> 
> Here are the steps:
> 
> 1. download zip file from "https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip" on browser or wget
> 2. extract zip file to static/microbit。
> 3. check "static\microbit\scratch-microbit-1.2.0.hex" exist
> 4. modify function "downloadMicrobitHex" in "scripts\prepublish.mjs" as follow to skip downloading and extracting, and read hex file directly from local instead.
> 
> ```
> const downloadMicrobitHex = async () => {
>     const relativeHexDir = path.join('static', 'microbit');
>     const hexFileName = "scratch-microbit-1.2.0.hex"
>     const relativeHexFile = path.join(relativeHexDir, hexFileName);
>     const relativeGeneratedDir = path.join('src', 'generated');
>     const relativeGeneratedFile = path.join(relativeGeneratedDir, 'microbit-hex-url.cjs');
>     const absoluteGeneratedDir = path.join(basePath, relativeGeneratedDir);
>     fs.mkdirSync(absoluteGeneratedDir, {recursive: true});
>     const absoluteGeneratedFile = path.join(basePath, relativeGeneratedFile);
>     fs.writeFileSync(
>         absoluteGeneratedFile,
>         [
>             '// This file is generated by scripts/prepublish.mjs',
>             '// Do not edit this file directly',
>             '// This file relies on a loader to turn this `require` into a URL',
>             `module.exports = require('./${path.relative(relativeGeneratedDir, relativeHexFile)}');`,
>             '' // final newline
>         ].join('\n')
>     );
>     console.info(`Wrote ${relativeGeneratedFile}`);
> };
> ```
> 
> @tomorrow307 @dbgoa @little8jie

谢！终于搞定！

**Comment by JiafengLiao** [comment]
> 已解决，多谢
> 
> 
> 
> 发自我的iPhone
> […](#)

赞！

**Comment by JiafengLiao** [comment]
> > Guys, Greetings from China, I solved it by manually downloading and extracting hex file plus a few lines of code modification.
> > Here are the steps:
> > 
> > 1. download zip file from "https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip" on browser or wget
> > 2. extract zip file to static/microbit。
> > 3. check "static\microbit\scratch-microbit-1.2.0.hex" exist
> > 4. modify function "downloadMicrobitHex" in "scripts\prepublish.mjs" as follow to skip downloading and extracting, and read hex file directly from local instead.
> > 
> > ```
> > const downloadMicrobitHex = async () => {
> >     const relativeHexDir = path.join('static', 'microbit');
> >     const hexFileName = "scratch-microbit-1.2.0.hex"
> >     const relativeHexFile = path.join(relativeHexDir, hexFileName);
> >     const relativeGeneratedDir = path.join('src', 'generated');
> >     const relativeGeneratedFile = path.join(relativeGeneratedDir, 'microbit-hex-url.cjs');
> >     const absoluteGeneratedDir = path.join(basePath, relativeGeneratedDir);
> >     fs.mkdirSync(absoluteGeneratedDir, {recursive: true});
> >     const absoluteGeneratedFile = path.join(basePath, relativeGeneratedFile);
> >     fs.writeFileSync(
> >         absoluteGeneratedFile,
> >         [
> >             '// This file is generated by scripts/prepublish.mjs',
> >             '// Do not edit this file directly',
> >             '// This file relies on a loader to turn this `require` into a URL',
> >             `module.exports = require('./${path.relative(relativeGeneratedDir, relativeHexFile)}');`,
> >             '' // final newline
> >         ].join('\n')
> >     );
> >     console.info(`Wrote ${relativeGeneratedFile}`);
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [@tomorrow307](https://github.com/tomorrow307) [@dbgoa](https://github.com/dbgoa) [@little8jie](https://github.com/little8jie)
> 
> 谢！终于搞定！

赞

**Comment by adriftj** [comment]
Hi guys,

The reason for this error is that node-fetch used by cross-fetch does not support proxy. You can make the following changes to scripts/prepublish.mjs.

First, add the following code at the beginning of the file:

```javascript
import { HttpsProxyAgent } from 'https-proxy-agent';
const proxyUrl = 'https://localhost:1080';
```

Then modify the line

```javascript
const response = await crossFetch(url);
```

in the function downloadMicrobitHex to

```javascript
const proxyAgent = new HttpsProxyAgent(proxyUrl);
const response = await crossFetch(url, { agent: proxyAgent });
```

Finally, re-execute npm install.

**Comment by rubingchupin** [comment]
我修改完后执行npm start出现了Module not found: Error: Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'E:\scratch-gui\src\generated'的问题，该如何解决？

**Comment by zthree2018** [comment]
> 按照上面给出的方案，可以正常运行成功；但是我在运行 npm start 启动的时候，报错： ERROR in ./src/generated/microbit-hex-url.cjs Module not found: Error: Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D:\Scratch\Scratch-Testing\scratch-gui\src\generated' 请问有没有什么好的解决方案？

我也遇到了相同的问题，有解决方法吗

**Comment by JiafengLiao** [comment]
> > 按照上面给出的方案，可以正常运行成功；但是我在运行 npm start 启动的时候，报错： ERROR in ./src/generated/microbit-hex-url.cjs Module not found: Error: Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D:\Scratch\Scratch-Testing\scratch-gui\src\generated' 请问有没有什么好的解决方案？
> 
> 我也遇到了相同的问题，有解决方法吗

看报错的话 文件路径是 ./....staticmicrobitscratch-microbit-1.2.0.hex，正常的话应该是 static\microbit\scratch-microbit-1.2.0.hex 应该是文件路径拼接的问题，你手动纠正这个路径的变量值 看下能不能解决

**Comment by xianzi2097** [comment]
> 按照上面给出的方案，可以正常运行成功；但是我在运行 npm start 启动的时候，报错： ERROR in ./src/generated/microbit-hex-url.cjs Module not found: Error: Can't resolve './....staticmicrobitscratch-microbit-1.2.0.hex' in 'D:\Scratch\Scratch-Testing\scratch-gui\src\generated' 请问有没有什么好的解决方案？

你好，豆包认为是路径的原因，我按她的指导修改可以运行成功：打开scratch-gui\src\generated文件里面的microbit-hex-url.cjs，文件内容改为：module.exports = "../static/microbit/scratch-microbit-1.2.0.hex";
