### ISSUE TITLE
Can not run it 

### ISSUE THREAD

**Issue by KenoChou** [LLK/scratch-gui#9788]
i clone this project on my pc but i can not run it 

**Screenshots**
> scratch-gui@5.1.18 prepublish
> node scripts/prepublish.mjs

Downloading https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip
FetchError: request to https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip failed, reason: connect ETIMEDOUT 2a03:2880:f107:83:face:b00c:0:25de:443
    at ClientRequest.<anonymous> (/home/keno/lab/web/react/scratch-gui/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:517:28)

**Comment by ELing9527** [comment]
> i clone this project on my pc but i can not run it
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> > scratch-gui@5.1.18 prepublish
> > node scripts/prepublish.mjs
> 
> Downloading https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip FetchError: request to https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip failed, reason: connect ETIMEDOUT 2a03:2880:f107:83:face:b00c:0:25de:443 at ClientRequest. (/home/keno/lab/web/react/scratch-gui/node_modules/node-fetch/lib/index.js:1501:11) at ClientRequest.emit (node:events:517:28)

手动下载 scratch-microbit.hex 下载连接 https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip 到项目的 tools （手动添加）文件下 然后 添加 gen-microbit-hex.js 文件 文件内容代码
`import fs from 'fs';
import path from 'path';

// 1. 读取本地 hex 文件
const hexPath = path.resolve('./tools/scratch-microbit.hex');
if (!fs.existsSync(hexPath)) {
    console.error('❌ 找不到 tools/scratch-microbit.hex，请先下载并放到 tools/ 目录');
    process.exit(1);
}

const hexContent = fs.readFileSync(hexPath, 'utf8');

// 2. 输出到 src/generated/microbit-hex-url.cjs
const outputDir = path.resolve('./src/generated');
const outputFile = path.join(outputDir, 'microbit-hex-url.cjs');
fs.mkdirSync(outputDir, {recursive: true});
fs.writeFileSync(outputFile, `module.exports = ${JSON.stringify(hexContent)};\n`);

console.log(`✅ 已生成 ${outputFile}`);`  后运行 node tools/gen-microbit-hex.js 后 执行 npm run start
